Finished
bartspreij/GroceryStore pull request #53
Opened 2024-01-24 13:55 UTC by TuT597

Prices are correctly displayed on every part of the website.

2024-01-25 09:50 UTC, bartspreij submitted a review, later dismissed

2024-01-25 09:51 UTC, bartspreij commented
Resolve merge conflict locally

2024-01-25 09:54 UTC, bartspreij requested changes
Resolve merge conflict locally

2024-01-26 14:42 UTC, melleg requested changes
ManageProducts is broken

2024-01-27 10:27 UTC, bartspreij approved these changes
Als je eslint regels uitzet dan liever bovenaan de file denk ik

2024-01-27 11:34 UTC, melleg requested changes

2024-01-27 11:34 UTC, melleg commented on frontend/src/components/discount/DiscountGallery.tsx
> -            const fetchedDiscounts = await fetchDiscountProducts();
This method should not be deleted

2024-01-27 11:47 UTC, TuT597 commented on frontend/src/components/discount/DiscountGallery.tsx
> -            const fetchedDiscounts = await fetchDiscountProducts();
Done

2024-01-27 11:47 UTC, merged

2024-01-27 11:47 UTC, melleg approved these changes